### ISSUE TITLE
preprints!

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/preprint.g8#2]
cc @marina-manrique @pablopareja @rtobes @laughedelic

**Comment by laughedelic** [comment]
cc!

**Comment by laughedelic** [comment]
:ok_hand:

**Comment by pablopareja** [comment]
nice! :smiley:

**Comment by pablopareja** [comment]
Just a quick question, what about references that are not necessarily articles? 
Should we also create them as `@article{` ?

**Comment by eparejatobes** [comment]
@pablopareja take a look at the [README](https://github.com/ohnosequences/preprint.g8#a-template-for-writing-preprints) (after #3 and #4)
